<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GameManaged>C:/Program Files (x86)/Steam/steamapps/common/Valheim/valheim_Data/Managed</GameManaged>
    <BepInExCore>C:/Program Files (x86)/Steam/steamapps/common/Valheim/BepInEx/core</BepInExCore>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine"><HintPath>$(GameManaged)/UnityEngine.dll</HintPath></Reference>
    <Reference Include="assembly_valheim"><HintPath>$(GameManaged)/assembly_valheim.dll</HintPath></Reference>
    <Reference Include="assembly_utils"><HintPath>$(GameManaged)/assembly_utils.dll</HintPath></Reference>
    <Reference Include="assembly_guiutils"><HintPath>$(GameManaged)/assembly_guiutils.dll</HintPath></Reference>
    <Reference Include="Splatform"><HintPath>$(GameManaged)/Splatform.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManaged)/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule"><HintPath>$(GameManaged)/UnityEngine.ScreenCaptureModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(GameManaged)/UnityEngine.ImageConversionModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(GameManaged)/UnityEngine.UI.dll</HintPath></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(GameManaged)/UnityEngine.UIModule.dll</HintPath></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(GameManaged)/Unity.TextMeshPro.dll</HintPath></Reference>
    <Reference Include="BepInEx"><HintPath>$(BepInExCore)/BepInEx.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>$(BepInExCore)/0Harmony.dll</HintPath></Reference>
  </ItemGroup>
</Project>
